### ISSUE TITLE
dataset

### ISSUE THREAD

**Issue by PoseidomWong** [KJoke70/prepare-dataset#2]
I'm sorry to bother you, but could you share this data set（FlickrLogos-47） with me？

**Comment by KJoke70** [comment]
I'm sorry, I'm not the owner of the dataset and I no longer have access to it. You will have to write an email to the owner.

From [https://www.uni-augsburg.de/en/fakultaet/fai/informatik/prof/mmc/research/datensatze/flickrlogos/](https://www.uni-augsburg.de/en/fakultaet/fai/informatik/prof/mmc/research/datensatze/flickrlogos/):

> Download
>
> If you wish to download one (or both of the datasets), please send an (informal) email to request_flickrlogos@informatik.uni-augsburg.de. Please state your name, your institution and why you would like to have access to this dataset (we are curious). We then send you a download link by e-mail.
>
> Note: This dataset consists of images downloaded from Flickr. Use of these images must respect Flickr's terms of use.

**Comment by PoseidomWong** [comment]
Thank you anyway.
